name: ci

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: sleep-3600
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: aureliendamien
          password: ${{ secrets.DOCKER_PASS }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: aureliendamien/su-info:sleep3600
